### ISSUE TITLE
In mobile phone, camera doesn't rendering problem 

### ISSUE THREAD

**Issue by EunjeYu** [8thwall/xr-unity#72] opened 2018-09-10 01:33 UTC
i have some question.
i use unity version 2018.1.6f1(64bit) and ios version, 11.4.
and in apple phone, the camera doesn't act. .  ... so i can see only skybox rendered by unity's mainCamera. 

I checked all below things.
What version of Unity are you running? (and what OS?) well done.
What type of phone are you using and what is the OS version?well done.
Do you have an XRController object in your scene (GameObject menu -> XRController), and is it's tag set to XRController? (8th Wall XR should configure the tag for you automatically)well done.
Select your XRController game object. In the inspector you should see an "XR Controller (Script)" attached. Make sure "Enable Camera" is checked.well done.
Under Edit -> Project Settings -> Graphics, scroll down towards the bottom of the GraphicsSettings inspector, and under "Always Included Shaders" you should see "Unlit/XRCameraShader" (8th Wall XR also should automatically configure this for you)well done.
and
my build setting - multithreaded Rendering ==> unenabled. ok.//well done.

and build setting is well done.

and switch platform well done. 

and XR app settings well done.

In unity - MainCamera has XRCamera Controller.cs, / XRController has XRController.cs / Plane has XR surface controller.cs .

**Comment by mralbean** [comment] 2018-09-10 02:02
Looks like this is a duplicate of https://github.com/8thwall/xr-unity/issues/70

Let's continue the issue discussion there.

**Closed by mralbean** 2018-09-10 02:02 UTC
